### PR TITLE
Use /usr/bin/env for compatibility

### PR DESCRIPTION
**Pull request by yggdr**

### CODE REVIEW

**Comment by frdmn** [comment]
:+1:

**Comment by shaneog** [comment]
:+1:

**Comment by denilsonsa** [comment]
Thanks!

I'm curious, in which systems is this an actual issue? I mean, what kind of system does not have `bash` in `/bin/`?

**Comment by yggdr** [comment]
Basically anything not Linux: FreeBSD, OpenBSD, Solaris, etc.

**Pull request merged**
